### ISSUE TITLE
Adjust task timeouts based on the overall time left

### ISSUE THREAD

**Issue by vlsi** [dotanuki-labs/gradle-timeouts-enforcer#5]
Currently, the plugin configures fixed timeout for all the tasks.
For instance, if I have `2 hour per build` and `30 min per task`, then the plugin should configure tasks in such a way, so the task that starts executing at `1h 50m` would get a timeout of 10m rather than 30m.

In other words, timeout should be `max(perTaskTimeout, overallBuildTimeLeft)`.

`Task#timeout` is `Property<Duration>`, so it should work if the property computes the actual value based on the time left.

**Comment by ubiratansoares** [comment]
Hi @vlsi,

Although I agree with you, I have two comments to point out :

- For the sake of just breaking the build when the "global" timeout is enforced, the timeout such `max(perTaskTimeout, overallBuildTimeLeft)` is not a thing at all, since the build timeout is driven by a delayed Coroutine execution as per `BuildTimeoutTracker` implementation

- I don't like the strategy of `BuildTimeoutTracker` at. 😹 

I'd happily move to a `max(perTaskTimeout, overallBuildTimeLeft)` timeout configured on-the-fly per task basis. Just to get your input : would be lazy configuration for Tasks your take here?

**Comment by ubiratansoares** [comment]
Hey @vlsi, I returned to this project after a few months and decided to ditch the support for the _overall time left_ from the plugin. I realized that it is just more convenient let one to define a proper timeout at CI job level instead, which accomplishes the same goal of enforcing a time-boxed execution for a set of any Gradle tasks (in an easier way)

This project was intended to explore a bit plugin development for Gradle from my end and I prefer to keep it simple for now. 

Thanks for your inputs anyway 🙂
